version: 2.1
description: Build Images with Cloud Native Buildpacks
orbs:
  cnb-orb:
    orbs:
      docker: circleci/docker@0.5.18
    jobs:
      build:
        docker:
          - image: circleci/golang:latest
        parameters:
          image-name:
            type: string
          builder:
            type: string
        steps:
          - setup_remote_docker:
              docker_layer_caching: true
          - checkout
          - run: mkdir /tmp/cache
          # - restore_cache:
          #     key: cnb-cache-<< parameters.image-name >>-<< parameters.builder >>-{{ arch }}
          - run:
              command: |
                docker run -d -v /workspace -v /tmp/cache --name builder << parameters.builder >> tail -f /dev/null
                docker cp /tmp/cache/. builder:/tmp/cache
                docker cp $PWD/. builder:/workspace
              name: Build container and copy contents
          - run:
              command: docker exec builder /cnb/lifecycle/detector
              name: Detect
          # - run:
          #     command: docker exec builder /cnb/lifecycle/restorer -path /tmp/cache
          #     name: Restore
          # - run:
          #     command: docker exec builder /cnb/lifecycle/analyzer << parameters.image-name >>
          #     name: Analyze
          - run:
              command: docker exec builder /cnb/lifecycle/builder
              name: Build
          # - run:
          #     command: docker exec builder /cnb/lifecycle/exporter << parameters.image-name >>
          #     name: Export
          # - run:
          #     command: docker exec builder /cnb/lifecycle/cacher -path /tmp/cache
          #     name: Cache
          # - save_cache:
          #     key: cnb-cache-<< parameters.image-name >>-<< parameters.builder >>-{{ arch }}-{{ epoch }}
          #     paths:
          #       - /tmp/cache
workflows:
  main:
    jobs:
      - cnb-orb/build:
          image-name: jabrown85/go-getting-started:cnb
          builder: heroku/buildpacks:18
